name: Test

on: [push]

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install Packages
        run: npm ci
      - name: Check Lint
        run: npm run lint
      - name: Test
        if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
        run: npm run test
      - name: Build
        run: npm run build:prod # this MUST be run to ensure production site will be built without errors
